import { AdminZenithPagesClient } from "@/components/admin/zenith/AdminZenithPagesClient";

export default function AdminZenithPagesPage() {
  return (
    <div className="space-y-2">
      <div>
        <h1 className="font-serif text-2xl text-foreground">Zenith Pages</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Review, preview, publish, and manage pages generated by ZenithMind.
        </p>
      </div>
      <div className="pt-4">
        <AdminZenithPagesClient />
      </div>
    </div>
  );
}
